# Generated by Django 3.0.3 on 2020-03-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='memo',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(default='', max_length=100, verbose_name='著者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='eval',
            field=models.CharField(choices=[('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], default=1, max_length=100, verbose_name='評価'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='kind',
            field=models.CharField(choices=[('Python', 'Python'), ('お金', 'お金'), ('ビジネス', 'ビジネス'), ('勉強', '勉強'), ('知識', '知識')], default=1, max_length=100, verbose_name='種別'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='review',
            field=models.TextField(default=1, max_length=400, verbose_name='レビュー'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='price',
            field=models.IntegerField(verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
