# Generated by Django 3.0.3 on 2020-03-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200323_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='eval',
            field=models.CharField(blank=True, choices=[('未読', '未読'), ('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], max_length=100, null=True, verbose_name='評価'),
        ),
    ]
